#!/bin/bash
# Structural and responsive-contract checks for the generated replay-lab HTML.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
REPORT="$ROOT/docs/replay-lab-report.html"

python3 "$ROOT/tools/render-replay-lab-report.py" --check

python3 - "$REPORT" "$ROOT" <<'PY'
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path
import sys


report = Path(sys.argv[1])
root = Path(sys.argv[2])
text = report.read_text(encoding="utf-8")


class Audit(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.ids = []
        self.fragment_links = []
        self.local_links = []
        self.copy_targets = []
        self.remote_assets = []
        self.decision_cards = 0

    def handle_starttag(self, tag, attrs):
        values = dict(attrs)
        if values.get("id"):
            self.ids.append(values["id"])
        classes = set((values.get("class") or "").split())
        if {"decision", "card"}.issubset(classes):
            self.decision_cards += 1
        if values.get("data-copy"):
            self.copy_targets.append(values["data-copy"])
        for name in ("href", "src"):
            value = values.get(name)
            if not value:
                continue
            if value.startswith(("http://", "https://", "//")):
                self.remote_assets.append(value)
            elif value.startswith("#"):
                self.fragment_links.append(value[1:])
            elif name == "href":
                self.local_links.append(value)


audit = Audit()
audit.feed(text)

errors = []
duplicates = sorted(key for key, count in Counter(audit.ids).items() if count > 1)
if duplicates:
    errors.append(f"duplicate id(s): {', '.join(duplicates)}")

id_set = set(audit.ids)
missing_fragments = sorted(set(audit.fragment_links) - id_set)
if missing_fragments:
    errors.append(f"fragment target(s) missing: {', '.join(missing_fragments)}")

missing_copy_targets = sorted(set(audit.copy_targets) - id_set)
if missing_copy_targets:
    errors.append(f"copy target(s) missing: {', '.join(missing_copy_targets)}")

for raw in audit.local_links:
    target = (report.parent / raw.split("#", 1)[0]).resolve()
    try:
        target.relative_to(root.resolve())
    except ValueError:
        errors.append(f"local reference escapes repository: {raw}")
        continue
    if not target.exists():
        errors.append(f"local reference missing: {raw}")

required_ids = {
    "thesis", "structure", "flow", "handoffs", "ticket", "comparison", "runbook",
    "scoring", "integrity", "scenarios", "boundaries", "references",
}
missing_sections = sorted(required_ids - id_set)
if missing_sections:
    errors.append(f"required section(s) missing: {', '.join(missing_sections)}")

required_text = [
    "Two folder trees, two different jobs",
    "One run path, two LLM contexts",
    "A follow-up another LLM can actually execute",
    "state: PREPARED",
    "state: SUBMITTED",
    "state: SCORED",
    "evaluate: retained",
    "bundled offline verifier",
    "replay-only owner tokens",
    "creates no coverage evidence",
    "run directory is the handle",
    "operator context could accidentally author the submission",
    "Same production validity, different decision quality",
    "decision coverage: PASS — 3/3 distinct decisions",
    "artifact: FAIL — production triage verifier exited 1",
    "Merged audit: rejected",
    "What I chose—and what I refused to claim",
    "Current source references",
    "@media (max-width: 1050px)",
    "@media (max-width: 720px)",
    "@media print",
]
for token in required_text:
    if token not in text:
        errors.append(f"required report contract missing: {token}")

if audit.decision_cards != 3:
    errors.append(f"expected 3 decision cards, found {audit.decision_cards}")
if audit.remote_assets:
    errors.append(f"remote asset/reference forbidden: {audit.remote_assets[0]}")
if not text.startswith("<!doctype html>"):
    errors.append("report must begin with <!doctype html>")
if text.count("<!-- GENERATED by tools/render-replay-lab-report.py. DO NOT EDIT BY HAND. -->") != 1:
    errors.append("generated-owner marker missing or duplicated")

if errors:
    for error in errors:
        print(f"REPORT: {error}")
    raise SystemExit(1)

print(
    "replay report tests: clean — sections, navigation, references, copy targets, "
    "calibrated decisions, and responsive contracts verified"
)
PY
